-- intermediate analysis

-- 1. Who are the top 10 customers by total spending?
select c.customer_id, concat(c.first_name," ", c.last_name) as customer_name, 
round((o.total_amount), 2) as total_spent from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_id, c.first_name, c.last_name, o.total_amount
order by total_spent desc limit 10;

-- 2. Which customers have placed more than 5 orders?
select c.customer_id, concat(c.first_name," ", c.last_name) as customer_name,
 count(o.order_id) as total_orders from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_id, c.first_name, c.last_name
having count(o.order_id) > 5
order by total_orders desc;

-- 3. What is the total revenue generated by each state?
select c.state, round(sum(total_amount), 2) as total_revenue from customers c
join orders o
on c.customer_id = o.customer_id
group by c.state 
order by total_revenue desc;

-- 4. Which cities generate the highest total sales revenue?
select c.city, round(sum(total_amount), 2) as total_revenue from customers c
join orders o
on c.customer_id = o.customer_id
group by c.city 
order by total_revenue desc;

-- 5. Find customers who have never placed an order?
select c.customer_id, concat(c.first_name," ", c.last_name) as customer_name from customers c
left join orders o
on c.customer_id = o.customer_id
where o.order_id is null;

-- 6. Which are the top 10 best-selling products by quantity sold?
select p.product_id, p.product_name, sum(oi.quantity) as total_quantity_sold from products p 
join order_items oi
on p.product_id = oi.product_id
group by p.product_id, p.product_name
order by total_quantity_sold desc limit 10;

-- 7. Which are the top 10 products generating the highest revenue??
select p.product_id, p.product_name, round(sum(oi.item_total), 2) as total_revenue from products p
join order_items oi
on p.product_id = oi.product_id
group by p.product_id, p.product_name
order by total_revenue desc limit 10;  

-- 8. How much revenue does each product category generate?
select p.category, round(sum(oi.item_total), 2) as total_revenue from products p 
join order_items oi
on p.product_id = oi.product_id
group by p.category
order by total_revenue desc;

-- 9. Which product categories have generated more than 1,00,000 in revenue?
select p.category, round(sum(oi.item_total), 2) as total_revenue from products p 
join order_items oi
on p.product_id = oi.product_id
group by p.category
having sum(oi.item_total) > 100000
order by total_revenue desc;

-- 10. Which products have low stock but high sales volume?
select p.product_id, p.product_name, p.stock_quantity, p.reorder_level,
 sum(oi.quantity) as total_quantity_sold from products p 
 join order_items oi
 on p.product_id = oi.product_id
 where p.stock_quantity < p.reorder_level
 group by p.product_id, p.product_name, p.stock_quantity, p.reorder_level
 having sum(oi.quantity) > (
	 select avg(total_quantity) 
	 from (select product_id, sum(quantity) as total_quantity from order_items
     group by product_id) as product_sales )
     order by total_quantity_sold desc;
	      
-- 11. . What is the total amount paid through each payment method for successful payments only?
select payment_method, round(sum(amount_paid), 2) as total_amount_paid from payments 
where payment_status = "paid"
group by payment_method
order by total_amount_paid desc;

-- 12.  Which payment methods have the highest number of failed transactions?
select payment_method, count(*) as failed_transactions from payments 
where payment_status = "Failed"
group by payment_method
order by failed_transactions desc;

-- 13.  Find orders where the order amount and paid amount don't match?
select o.order_id, o.total_amount as order_amount, p.amount_paid, p.payment_status from orders o 
join payments p 
on o.order_id = p.order_id
where o.total_amount != p.amount_paid;

-- 14. What percentage of total orders were cancelled or returned?
select round( sum( case
                       when order_status in ("cancelled", "returned")
                       then 1
                       else 0
				   end) * 100.0 / count(*), 2) as cancelled_returned_percentage
			 from orders;
			
-- 15. Find the monthly revenue and identify which month had the highest revenue            
select year(order_date) as order_year, month(order_date) as order_month,
 round(sum(total_amount), 2) as monthly_revenue from orders 
group by year(order_date), month(order_date) 
order by monthly_revenue desc limit 1;
